<!DOCTYPE classificacion [
<!ELEMENT mundial (mundial*)>
<!ELEMENT mundial (pais+)>
<!ELEMENT mundial pais CDATA #REQUIRED>
<!ELEMENT pais (nombre, region?, division?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT desclasificacion (#PCDATA)>
]
<mundial>
    <mundial tipo="mundial">
        <pais>
            <nombre>Espa√±a</nombre>
            <desclasificacion>Octavos</desclasificacion>
        </pais>
        <pais>
            <nombre>Alemania</nombre>
            <desclasificacion>Fase de grupos</desclasificacion>
        </pais>
    </mundial>